build/Procfile
build/bin/post-compile

- 删除 build/Procfile, build/bin
- Fixes #

remove unused build files

---

pkg/logging/init.go

- 修复web logger配置引用错误
- Fixes #

bugfix: wrong config for web logger

---

go.mod
go.sum
pkg/config/config.go
pkg/middleware/ratelimit.go
pkg/server/router.go
pkg/util/error.go
pkg/util/response.go
vendor/golang.org/x/time/AUTHORS
vendor/golang.org/x/time/CONTRIBUTORS
vendor/golang.org/x/time/LICENSE
vendor/golang.org/x/time/PATENTS
vendor/golang.org/x/time/rate/rate.go
vendor/modules.txt

- add api rate-limit, for calling api directly
- Fixes #

add api rate-limit, for the calling directly

---

pkg/abac/pdp/translate/expression.go

- fix code review comment, move any merge into for loop before
- Fixes #

refactor merge any in translate

---

pkg/abac/pdp/condition/and.go
pkg/abac/pdp/condition/or.go

fix(lints): fix lints, change if-elif-else to switch

---

pkg/api/model/handler/instance_selection_check.go

fix: fix check instance selection quota

---

pkg/api/web/handler/action_slz.go

- fix action support fields
- Fixes #

fix: fix action support fields

---

pkg/abac/pdp/evalctx/context.go
pkg/abac/pdp/evalctx/context_test.go
pkg/abac/pdp/evaluation/evaluation.go

- 修复问题: 不传递资源时环境属性没有处理
- Fixes #

Bugfix partial eval no resources

---

go.mod
go.sum
vendor/github.com/TencentBlueKing/iam-go-sdk/expression/eval/compare.go
vendor/modules.txt

- 修复数值比较传入nil导致的panic
- Fixes #

fix(pdp/eval): numveric_cmp panic if got nil

---

pkg/api/model/handler/action.go
pkg/api/model/handler/types.go
pkg/database/dao/model_change_event.go
pkg/service/model_change_event.go

- 删除Action时，对于立即删除的情况，需要处理其delete policy 事件
- Fixes #

fix(delete action): delete policy event error where action be deleted

---

readme.md
readme_en.md

docs(readme.md): add bk-iam-cli links

---

Makefile

- 支持M1 Mac 执行Go test
- Fixes #

docs(makefile): update `make test` since m1 mac

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
pkg/abac/prp/mock/policy.go
pkg/abac/prp/policy.go
pkg/abac/prp/policy_curd.go
pkg/abac/prp/policy_curd_test.go
pkg/abac/prp/temporary_policy_test.go
pkg/api/web/handler/temporary_policy.go
pkg/api/web/handler/temporary_policy_slz.go
pkg/api/web/router.go
pkg/database/dao/mock/temporary_policy.go
pkg/database/dao/temporary_policy.go
pkg/database/dao/temporary_policy_test.go
pkg/service/mock/temporary_policy.go
pkg/service/temporary_policy.go
pkg/service/temporary_policy_test.go
test/iam.postman_collection.json
test/init.sql

<!--
请保证PR标题明确清晰, 易于理解
Keep PR title verbose enough
- 新增临时权限 web api
- Fixes # https://github.com/TencentBlueKing/bk-iam-saas/issues/779

Ft temporary policy

---

release.md

release.md

---

pkg/api/model/handler/action.go
pkg/api/web/handler/action.go
pkg/api/web/handler/action_slz.go
pkg/cacheimpls/action_list.go
pkg/cacheimpls/action_list_test.go
pkg/cacheimpls/deleter.go
pkg/cacheimpls/init.go
pkg/cacheimpls/types.go

feat(action): add list_action cache for web

---

pkg/api/model/handler/action.go
pkg/api/model/handler/action_check.go
pkg/api/model/handler/instance_selection.go
pkg/api/model/handler/policy.go
pkg/api/model/handler/resource_type.go
pkg/api/model/handler/types.go
pkg/api/web/handler/model_change_event.go
pkg/api/web/handler/model_change_event_slz.go
pkg/api/web/router.go
pkg/database/dao/dao_suite_test.go
pkg/database/dao/mock/model_change_event.go
pkg/database/dao/model_change_event.go
pkg/database/dao/model_change_event_test.go
pkg/service/mock/action.go
pkg/service/mock/model_change_event.go
pkg/service/mock/system_config.go
pkg/service/model_change_event.go
pkg/service/model_change_event_test.go

feat(model event): add delete api

---

build/support-files/sql/0020_iam_20220424-1622_mysql.sql

fix(sql): missing semicolon

---

pkg/database/dao/model_change_event.go
pkg/database/dao/model_change_event_test.go

style(sql): 'form -> from ' spell wrong

---

build/support-files/sql/0021_iam_20220601-1635_mysql.sql
pkg/api/model/handler/action.go
pkg/api/model/handler/action_check.go
pkg/api/model/handler/action_slz.go
pkg/api/model/handler/util.go
pkg/database/sdao/saas_action.go
pkg/service/action.go
pkg/service/types/action.go

- xxxx
- Fixes https://github.com/TencentBlueKing/bk-iam-saas/issues/1106

feat(action/create): add auth_type in action create

---

build/support-files/sql/0021_iam_20220517-1502_mysql.sql
pkg/abac/pap/group.go
pkg/abac/pap/group_test.go
pkg/abac/pap/mock/group.go
pkg/abac/pap/types.go
pkg/api/web/handler/group.go
pkg/api/web/handler/group_test.go
pkg/cacheimpls/init.go
pkg/database/dao/mock/subject_relation.go
pkg/database/dao/subject_relation.go
pkg/database/dao/subject_relation_test.go
pkg/service/group.go
pkg/service/group_test.go
pkg/service/mock/group.go
pkg/service/types/subject.go
test/init.sql

- 缩减subject_relation表字段
- Fixes #https://github.com/TencentBlueKing/bk-iam-saas/issues/1075

Ft update subject relation

---

.github/workflows/go.yml
Makefile
pkg/api/web/handler/action_slz.go
pkg/cacheimpls/init.go
pkg/service/action.go
pkg/service/types/action.go

fix https://github.com/TencentBlueKing/bk-iam-saas/issues/1144
- xxxx
- Fixes #

feat(api/web): add action auth_type in list/get apis

---

pkg/database/dao/model_change_event.go
pkg/database/sdao/saas_action.go
pkg/database/sdao/saas_instance_selection.go
pkg/database/sdao/saas_resource_type.go
pkg/database/sdao/saas_system.go
pkg/database/sdao/saas_system_config.go
pkg/database/utils_test.go

- 修复某些情况下sql报错导致用户接口 500 
- Fixes [#](https://github.com/TencentBlueKing/bk-iam-saas/issues/1048)

fix(model/update): emtpy model update sql syntax error

---

go.mod
go.sum
pkg/database/dao/mock/resource_type.go
pkg/database/dao/resource_type_test.go
pkg/service/action_resource_type.go
pkg/service/action_resource_type_test.go
vendor/github.com/agiledragon/gomonkey/v2/README.md
vendor/github.com/agiledragon/gomonkey/v2/creflect/ae1.17.go
vendor/github.com/agiledragon/gomonkey/v2/creflect/be1.16.go
vendor/github.com/agiledragon/gomonkey/v2/creflect/type.go
vendor/github.com/agiledragon/gomonkey/v2/jmp_386.go
vendor/github.com/agiledragon/gomonkey/v2/modify_binary_darwin.go
vendor/github.com/agiledragon/gomonkey/v2/modify_binary_linux.go
vendor/github.com/agiledragon/gomonkey/v2/patch.go
vendor/modules.txt

test(action detail cache): add unittest

---

pkg/api/model/handler/share.go
pkg/api/model/handler/system_slz.go
pkg/api/model/router.go

- 下线系统列表api
- Fixes https://github.com/TencentBlueKing/bk-iam-saas/issues/1184

refactor(remove/api): remove share list sytems api

---

pkg/abac/pip/subject_test.go
pkg/cacheimpls/init.go
pkg/cacheimpls/local_subject_department.go
pkg/cacheimpls/local_subject_department_test.go
pkg/service/subject_system_group.go
test/iam.postman_collection.json
test/init.sql

- local subject department cache
- Fixes #

local subject department cache

---

pkg/abac/pap/policy_v2.go
pkg/abac/pdp/condition/string_prefix.go
pkg/abac/pdp/condition/string_prefix_test.go
pkg/abac/pdp/evalctx/context.go
pkg/abac/pdp/evalctx/context_test.go
pkg/abac/pdp/rbac.go
pkg/abac/pdp/rbac_test.go
pkg/abac/types/action.go
pkg/cacheimpls/deleter.go
pkg/cacheimpls/group_resource_policy.go
pkg/cacheimpls/group_resource_policy_test.go
pkg/cacheimpls/init.go
pkg/cacheimpls/local_resource_type_pk.go
pkg/cacheimpls/local_resource_type_pk_test.go
pkg/cacheimpls/resource_type_pk.go
pkg/cacheimpls/resource_type_pk_test.go
pkg/database/dao/mock/resource_type.go
pkg/database/dao/resource_type.go
pkg/database/dao/resource_type_test.go
pkg/service/action_resource_type.go
pkg/service/action_resource_type_test.go
pkg/service/mock/resource_type.go
pkg/service/resource_type.go
pkg/service/types/action_detail.go

update group resource policy cache

---

pkg/abac/pap/group.go
pkg/abac/pap/mock/group.go
pkg/abac/pap/policy_curd.go
pkg/abac/pap/policy_curd_test.go
pkg/abac/pap/types.go
pkg/api/web/handler/group.go
pkg/database/dao/subject_group.go
pkg/service/group.go
pkg/service/mock/temporary_policy.go
pkg/service/temporary_policy.go
pkg/service/temporary_policy_test.go
pkg/service/types/subject.go

- CreateAt to CreatedAt
- ExpireAt to ExpiredAt
- Fixes #

Fix typo 0706

---

pkg/logging/debug/pool.go

fix: debug entry put clear error

---

build/support-files/sql/0024_iam_20220523-0740_mysql.sql
build/support-files/sql/0026_iam_20220718-1535_mysql.sql
pkg/database/dao/group_resource_policy.go
pkg/database/dao/group_resource_policy_test.go

- add rbac sync db tables
- Fixes #

feat(rbac_group_resource_policy): add rbac sync tables

---

pkg/abac/pdp/condition/init.go
pkg/abac/pdp/condition/numeric_cmp.go
pkg/abac/pdp/condition/numeric_cmp_test.go
pkg/abac/pdp/condition/operator/types.go
pkg/abac/pdp/condition/string_contains.go
pkg/abac/pdp/condition/string_contains_test.go
pkg/abac/pdp/condition/string_prefix.go

- 增加StringContains运算支持
- Fixes #

feat(abac/pdp): add string_contains operator

---

build/support-files/sql/0022_iam_20220517-1502_mysql.sql
build/support-files/templates/#etc#supervisor-bkiam.conf

build: add worker/checker command

---

pkg/abac/prp/rbac/convert/subject_action_expression.go
pkg/abac/prp/rbac/convert/subject_action_expression_test.go

bugfix: mergeGroupResource duplicate resource id

---

build/support-files/templates/#etc#bkiam_config.yaml
cmd/init.go
config.yaml.tpl
pkg/abac/pap/policy_rbac.go
pkg/abac/prp/policy.go
pkg/config/init.go
pkg/service/group_resource_policy.go
pkg/service/group_resource_policy_test.go
pkg/service/mock/group_resource_policy.go
pkg/task/checker.go
pkg/task/consumer/redis.go

bugfix: policy manger ListBySubjectAction deduplication

---

pkg/task/consumer/redis.go

feat(task/worker): add consumer stats for logging

---

pkg/task/transfer.go

feat(pkg/task/transfer.go): transform loop

---

pkg/task/transfer.go

Ft rbac sync

---

build/support-files/sql/0026_iam_20220718-1535_mysql.sql
pkg/database/dao/mock/subject_action_alter_event.go
pkg/database/dao/subject_action_alter_event.go
pkg/database/dao/subject_action_alter_event_test.go
pkg/service/mock/subject_action_alter_event.go
pkg/service/subject_action_alter_event.go
pkg/task/checker.go
pkg/task/init.go

- xxxx
- Fixes 
https://github.com/TencentBlueKing/bk-iam-saas/issues/1350

feat(pkg/task/checker.go): add subject action alter event checker

---

pkg/abac/prp/helper.go
pkg/abac/prp/helper_test.go
pkg/api/common/init.go
pkg/api/common/init_test.go
pkg/api/web/handler/group.go
pkg/api/web/handler/group_check.go
pkg/api/web/handler/group_test.go
pkg/cacheimpls/system_subject_group.go
pkg/cacheimpls/system_subject_group_test.go
pkg/config/config.go

- xxxx
- Fixes #
https://github.com/TencentBlueKing/bk-iam-saas/issues/1227

feat(pkg/api/web/group_check.go): add subject system group limit check

---

pkg/abac/pdp/entrance.go
pkg/abac/pdp/entrance_test.go
pkg/abac/pdp/helper.go
pkg/abac/pdp/helper_test.go
pkg/abac/prp/mock/policy.go
pkg/abac/prp/policy.go
pkg/database/dao/mock/subject_action_alter_event.go
pkg/service/mock/subject_action_alter_event.go
pkg/task/checker.go
pkg/task/transfer.go

- auth api without query rbac policies
- Fixes #

feat: auth api without query rbac policies

---

pkg/api/basic/handler/healthz.go

bugfix: healthz check redis

---

pkg/config/config.go
pkg/config/init.go
pkg/task/consumer/redis.go

feat: create 3 consumer per process

---

pkg/api/web/handler/group.go
pkg/api/web/handler/subject_slz.go
pkg/api/web/router.go

- xxxx
- Fixes https://github.com/TencentBlueKing/bk-iam-saas/issues/1369

feat: add subject group quota check api

---

cmd/checker.go
cmd/iam.go
cmd/transfer.go
cmd/worker.go
pkg/config/config.go
pkg/metric/init.go
pkg/metric/rmq.go
pkg/server/router.go
pkg/server/server.go
pkg/server/server_test.go
pkg/task/checker.go
pkg/task/consumer/redis.go
pkg/task/consumer/redis_test.go
pkg/task/init.go
pkg/task/stats/stats.go
pkg/task/transfer.go

- xxxx
- Fixes https://github.com/TencentBlueKing/bk-iam-saas/issues/1345

feat: add task stats metrics

---

build/support-files/sql/0027_iam_20220914-1502_mysql.sql
pkg/abac/pap/types.go
pkg/api/web/handler/group.go
pkg/api/web/handler/group_test.go
pkg/api/web/handler/subject_slz.go
pkg/database/dao/subject_group.go
pkg/database/dao/subject_group_test.go

refactor: change policy_expired_at to expired_at

---

pkg/api/web/router.go

- xxxx
- Fixes https://github.com/TencentBlueKing/bk-iam-saas/issues/720

feat: remove web unused router

---

pkg/api/model/handler/action.go
pkg/api/model/handler/action_check.go

bugfix: action delete check policy exists

---

pkg/abac/pap/group.go
pkg/api/model/handler/system_config.go
pkg/api/web/handler/system_settings.go
pkg/service/system_config.go

feat: add custom frontend settings config

---

pkg/abac/pap/group.go
pkg/abac/pap/group_test.go
pkg/api/web/router.go
pkg/database/dao/mock/subject_group.go
pkg/database/dao/subject_group.go
pkg/database/dao/subject_group_test.go
pkg/database/mysql.go
pkg/service/group.go
pkg/service/group_test.go
pkg/service/mock/group.go

feat: update web api subject group belong

---

pkg/database/mysql.go

fix: mysql time zone init

---

pkg/util/json/go_json.go
pkg/util/json/json.go

fix: update pkg/util/json

---

pkg/service/action.go
pkg/service/resource_type.go

bugfix: action resource_type model share api add sensitivity

---

build/support-files/sql/0029_iam_20221219-1645_mysql.sql
pkg/database/dao/subject.go
pkg/database/dao/subject_department.go

fix: update sql

---

build/support-files/sql/0029_iam_20221219-1645_mysql.sql

build: update subject name max length to 512

---

pkg/database/dao/open_abac_policy.go
pkg/database/dao/open_rbac_policy.go
pkg/database/dao/subject.go
pkg/database/dao/subject_department.go

fix: limit offset

---

build/support-files/sql/0030_iam_20230411-1017_mysql.sql
pkg/abac/prp/temporary/policy.go
pkg/api/model/handler/action.go
pkg/api/model/handler/action_slz.go
pkg/api/web/handler/action_slz.go
pkg/database/sdao/saas_action.go
pkg/service/action.go
pkg/service/types/action.go
test/init.sql

feat: action add hidden field

---

pkg/database/dao/expression.go
pkg/database/dao/expression_test.go
pkg/database/dao/mock/expression.go
pkg/service/policy.go

fix: batch delete unreferenced expressions

---

pkg/api/model/handler/action.go

- 修改 action 接口 path 
- path 为  /api/v1/model/systems/{system_id}/action/{action_id} 变更为  /api/v1/model/systems/{system_id}/actions/{action_id}
- 删除 action  接口 path
- path 为  /api/v1/model/systems/{system_id}/action/{action_id} 变更为  /api/v1/model/systems/{system_id}/actions/{action_id}

fix(apidoc): 模型注册 => 操作 Action API path 不对

---

pkg/database/dao/subject_system_group.go
pkg/database/dao/subject_system_group_test.go

bugfix: subject system groups sql for mysql 8.0

---

pkg/api/model/handler/action.go
pkg/api/model/handler/action_slz.go
pkg/service/action.go

bugfix: action update with hidden

---

pkg/database/dao/policy.go

feat: update policy list order

---

pkg/abac/pap/group.go
pkg/abac/pap/types.go
pkg/cacheimpls/init.go
pkg/cacheimpls/local_subject.go
pkg/cacheimpls/local_subject_test.go
pkg/database/dao/mock/subject.go
pkg/database/dao/subject.go
pkg/database/dao/subject_test.go
pkg/service/mock/subject.go
pkg/service/subject.go
pkg/service/subject_test.go
pkg/service/types/subject.go

feat: add subject cache batch get

---

build/support-files/sql/0032_iam_20231214-1600_mysql.sql

feat: optimize performance by adding indexes

---

pkg/abac/pap/group.go
pkg/abac/pap/group_test.go
pkg/service/group.go
pkg/service/group_test.go
pkg/service/mock/group.go
pkg/service/types/subject.go

update: belong api add source

---

build/bkpkg-bkiam.yaml

add: bkpkg yaml file

---

pkg/api/model/handler/action.go
pkg/api/model/handler/instance_selection.go
pkg/api/model/handler/query.go
pkg/api/model/handler/resource_type.go
pkg/api/model/handler/system.go
pkg/api/model/handler/system_config.go
pkg/api/model/handler/token.go

Fix model api doc

---

Dockerfile
pkg/cache/redis/init.go
pkg/config/config.go
pkg/database/mysql.go
pkg/util/tls.go

feat: support tls

---

.github/workflows/go.yml

ci: github action
